### ISSUE TITLE
acquire is a  Protected Method

### ISSUE THREAD

**Issue by mneckoee** [Mentalab-hub/explore-android#61]
this method should be a public method

https://github.com/Mentalab-hub/explore-android/blob/79106664a842ddcfb34b3ecb1c0cd647bed1c430/mentalabMobileApi/src/main/java/com/mentalab/ExploreDevice.java#L63

**Comment by salman2135** [comment]
Thanks for mentioning this issue. We fixed this problem in our [develop](https://github.com/Mentalab-hub/explore-android/blob/a203093a15630e136a607f07c85d4643909d6d7f/mentalabMobileApi/src/main/java/com/mentalab/ExploreDevice.java#L93) branch.

Hope that solves this problem.
